---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "Improving accuracy and speeding up Document Image Classication through parallel systems"
keywords:    "SinglePaged, jekyll, template, github, blog, single page"
description: "Site for improving accuracy paper"
source_link: "https://github.com/javiferran/document-classification"
favicon:     "img/BSC-Logo.ico"
touch_icon:  "img/BSC-Logo.jpg"
google_analytics_key: UA-49607422-1 ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#ffffff'
  blue:      '#49a7e9'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'
  color1:	'#DCBB7D'
  color5:	'#757575'
  light_green: '#baeba0'
  light_blue: '#8fdaff'

kramdown:
  auto_ids:  false

##f8f8f8
